<html>
    <head></head>
    <body>
        <h3>Revolution Jewels - Contact Form Submitted</h3>
        <p>Someone has submitted contact form</p>
        
        <p><strong>Full Name: </strong><?php echo $fullname; ?></p>
        <p><strong>Subject: </strong><?php echo $subject; ?></p>
        <p><strong>Order Number: </strong><?php echo $ordernumber; ?></p>
        <p><strong>Email Address: </strong><?php echo $email; ?></p>
        <p><strong>Phone: </strong><?php echo $phone; ?></p>
        <p><strong>Message:</strong> </p>
        <p>
           <?php echo $message; ?>
        </p>
        
        <p>------------</p>
        <p>This is autogenerated email.</p>
    </body>
</html>